#!/bin/bash
# Build MQMGateway and Home Assistant config files from template files and
# apply it to modmqttd.  Arguments:
#
#	-d = debug mode, generate the config file without applying it.
#	-m = Only generate MQTT config, not HA config.
#	-v = verbose mode, show each template generation.
#
# To control what goes into the config file, scroll down to the section
# with the comment '# Edit the following'.

CONFIG_FILE_DIRECTORY=""
HEADER_FILE_MQTT="config_header_mqtt.yaml"
HEADER_FILE_HA="config_header_ha.yaml"
OUTPUT_FILE_MQTT="config.yaml"
OUTPUT_FILE_HA="home_assistant.yaml"
OUTPUT_FILE_HA_JSON="home_assistant.json"
DEBUG=0
MQTT_ONLY=0
VERBOSE=0

# Process any optional flags before the args.

while getopts "dmv" options ; do
	case "${options}" in
		d) DEBUG=1 ;;
		m) MQTT_ONLY=1 ;;
		v) VERBOSE=1 ;;
		*) echo "Invalid option -${OPTARG}" >&2 ;
		   exit 1 ;;
	esac
done
shift $(( OPTIND - 1 ))

# Check whether the config files are in a subdirectory.

if [ -d "templates" ] ; then
	CONFIG_FILE_DIRECTORY="templates/"
fi

# Check for common problems in template files.  Using a register value of 0
# is particularly problematic since it gets converted to -1, which makes the
# resulting error message look like it's an error return value from a
# libmodbus function.  Using invisible-to-the-editor tabs is also a problem,
# better to catch this at this stage than later when they're in the config
# file.

for file in "${CONFIG_FILE_DIRECTORY}"*.yamlt ; do
	if [ "$(grep -c '^\s*register:\s*0\b' $file)" -gt 0 ] ; then
		echo "Template $file uses 0-based registers, should be 1-based" >&2 ;
		exit 1 ;
	fi
	if [ "$(grep -c $'\t' $file)" -gt 0 ] ; then
		echo "Template $file contains tab characters, should be spaces" >&2 ;
		exit 1 ;
	fi
done

# Create the header.  This performs DNS lookups on the named devices and
# inserts the corresponding IP addresses into the header for the config
# file

compile_header()
	{
	for DNSNAME in "$@" ; do

		# Get the IP address of the device.  This isn't very fancy, it just
		# returns the first one found without much checking on the assumption
		# that an embedded modbus gateway isn't going to be multihomed.
		IP_ADDRESS=$(dig +short "$DNSNAME" | head -n1)
		if [ -z "$IP_ADDRESS" ] ; then
			echo "No DNS entry for server $DNSNAME" >&2 ;
			exit 1 ;
		fi

		if [ $VERBOSE -eq 1 ] ; then
			echo "Setting address for ${DNSNAME} to ${IP_ADDRESS}" ;
		fi

		# Swap out the DNS name for the IP address
		sed -i s/"${DNSNAME}"/"${IP_ADDRESS}"/g ${OUTPUT_FILE_MQTT}

	done
	}

# Add information to an output file describing how the current section
# was generated.

add_build_info()
	{
	NAME=$1
	TEMPLATE_FILE=$2
	OUTPUT_FILE=$3

	echo "" >> "${OUTPUT_FILE}"
	echo "    # Sensor group '${NAME}' added from '${TEMPLATE_FILE}' template" >> "${OUTPUT_FILE}"
	}

# Create an output file from a template file.  This just strips comments
# and inserts the topic, network name, and address at the appropriate
# locations.

compile_template_ha()
	{
	TEMPLATE_FILE=$1
	TOPIC=$2
	NAME=$3

	if [ $VERBOSE -eq 1 ] ; then
		echo "Creating sensor group ${TOPIC} from ${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_ha.yamlt" ;
	fi

	if [ ! -f "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_ha".yamlt ] ; then
		echo "Template ${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_ha.yamlt not found" >&2 ;
		exit 1 ;
	fi
#	if [ ! -f "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_ha".jsont ] ; then
#		echo "Template ${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_ha.jsont not found" >&2 ;
#		exit 1 ;
#	fi

	add_build_info "$NAME" "${TEMPLATE_FILE}" "${OUTPUT_FILE_HA}"
	cat "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}"_ha.yamlt | sed '/^#/d' | sed s/XXXX/"${TOPIC}"/g >> "${OUTPUT_FILE_HA}"

#	cat "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}"_ha.jsont | sed '/^#/d' | sed s/YYYY/"${NAME}"/g >> "${OUTPUT_FILE_HA_JSON}"
	}

compile_template()
	{
	TEMPLATE_FILE=$1
	TOPIC=$2
	NAME=$3
	NETWORK=$4
	ADDRESS=$5

	if [ $VERBOSE -eq 1 ] ; then
		echo "Creating topic ${TOPIC} from ${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_mqtt.yamlt" ;
	fi

	if [ ! -f "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_mqtt".yamlt ] ; then
		echo "Template ${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}_mqtt.yamlt not found" >&2 ;
		exit 1 ;
	fi

	add_build_info "$NAME" "${TEMPLATE_FILE}" "${OUTPUT_FILE_MQTT}"
	cat "${CONFIG_FILE_DIRECTORY}${TEMPLATE_FILE}"_mqtt.yamlt | sed '/^#/d' | sed s/XXXX/"${TOPIC}"/g | sed s/YYYY/"${NETWORK}"/g | sed s/ZZZZ/"${ADDRESS}"/g >> "${OUTPUT_FILE_MQTT}"

	if [ $MQTT_ONLY -ne 1 ] ; then
		compile_template_ha "$TEMPLATE_FILE" "$TOPIC" "$NAME";
	fi
	}

# "Compile" the input files into the config files.  The argument order
# for is 'template_file topic_name friendly_name network address'.

if [ -f ${OUTPUT_FILE_MQTT} ] ; then
	rm ${OUTPUT_FILE_MQTT} ;
fi
if [ -f ${OUTPUT_FILE_HA} ] ; then
	rm ${OUTPUT_FILE_HA} ;
fi

echo "# This file has been auto-generated by mkconfig.sh." > "${OUTPUT_FILE_MQTT}"
echo "# Any changes will be overwritten on the next rebuild." >> "${OUTPUT_FILE_MQTT}"
echo "" >> "${OUTPUT_FILE_MQTT}"
cat ${CONFIG_FILE_DIRECTORY}${HEADER_FILE_MQTT} >> ${OUTPUT_FILE_MQTT}

echo "# This file has been auto-generated by mkconfig.sh." > "${OUTPUT_FILE_HA}"
echo "# Any changes will be overwritten on the next rebuild." >> "${OUTPUT_FILE_HA}"
echo "" >> "${OUTPUT_FILE_HA}"
cp ${CONFIG_FILE_DIRECTORY}${HEADER_FILE_HA} ${OUTPUT_FILE_HA}

touch "${OUTPUT_FILE_HA_JSON}"

#########################################################################
# Edit the following section to control what goes into the config file.
#########################################################################

compile_header outdoors.modbus.lan indoors.modbus.lan basement.modbus.lan

compile_template eastron grid indoors 10
compile_template eastron non_backup indoors 11
compile_template eastron backup indoors 12
compile_template eastron heating indoors 13
compile_template eastron hot_water indoors 14

compile_template waveshare_io waveshare_io indoors 20

compile_template pulse_count water indoors 21

compile_template temp_humid basement basement 10

compile_template temp_humid front_door outdoors 10
compile_template temp_humid back_door outdoors 11
compile_template temp_humid shed outdoors 12

compile_template water_level water_tank outdoors 20

#########################################################################
# End of user-defined configuration settings
#########################################################################

# If we're running in debug mode only, don't apply the changes

if [ $DEBUG -eq 1 ] ; then
	exit 0 ;
fi

# Install the new config file and restart modmqttd.  We need to pause
# for a second after the restart to allow modmqttd time to initialise.

sudo cp config.yaml /etc/modmqttd/config.yaml
sudo systemctl restart modmqttd
sleep 1
sudo systemctl status modmqttd | less
